console.log("05 Context is in learning mode.")
console.log("[x] 01 Full Session As Context")
console.log("[x] 02 Explicit Context Builder")
console.log("[x] 03 Context Sources")
console.log("[x] 04 History Selection")
console.log("[>] 05 Safe Context Units")
console.log("[ ] 06 Minimal Context Runtime")
console.log("Current: npm run context:05")
