console.log("Integration · Mini Coding Agent is in learning mode.")
console.log("[x] 01 Agent Skeleton")
console.log("[x] 02 Read → Think → Answer")
console.log("[x] 03 Read → Edit → Permission → Write")
console.log("[>] 04 Multi-Step Coding Loop")
console.log("[ ] 05 Session / Context / Recovery")
console.log("[ ] 06 Minimal Coding Agent Runtime")
console.log("Current: npm run integration:04")
