console.log("06 Compaction is in learning mode.")
console.log("[x] 01 No Compaction")
console.log("[x] 02 Compaction Trigger")
console.log("[x] 03 Hot / Cold Context")
console.log("[>] 04 Summarize Cold Context")
console.log("[ ] 05 Rebuild Compacted Context")
console.log("[ ] 06 Minimal Compaction Runtime")
console.log("Current: npm run compaction:04")
