console.log("06 Compaction is in learning mode.")
console.log("[>] 01 No Compaction")
console.log("[ ] 02 Compaction Trigger")
console.log("[ ] 03 Hot / Cold Context")
console.log("[ ] 04 Summarize Cold Context")
console.log("[ ] 05 Rebuild Compacted Context")
console.log("[ ] 06 Minimal Compaction Runtime")
console.log("Current: npm run compaction:01")
