console.log("08 Recovery is in learning mode.")
console.log("[x] 01 No Recovery")
console.log("[x] 02 Retry")
console.log("[x] 03 Run State")
console.log("[>] 04 Checkpoint / Snapshot")
console.log("[ ] 05 Resume / Rollback")
console.log("[ ] 06 Minimal Recovery Runtime")
console.log("Current: npm run recovery:04")
