console.log("07 Permission is in learning mode.")
console.log("[x] 01 No Permission")
console.log("[x] 02 Allow / Deny")
console.log("[>] 03 Ask Before Execute")
console.log("[ ] 04 Resource Scope")
console.log("[ ] 05 Policy Precedence")
console.log("[ ] 06 Minimal Permission Runtime")
console.log("Current: npm run permission:03")
